[package]
name = "shpack"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
clap = { version = "4.5.43", features = ["cargo"] }
color-eyre = "0.6.5"
tree-sitter = "0.25"
tree-sitter-bash = "0.25"
